# Generated by Django 4.2.5 on 2023-10-06 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work_01_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='photo',
            field=models.ImageField(default=None, null=True, upload_to='media/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(default=None, null=True),
        ),
    ]
