# Generated by Django 4.2.5 on 2023-09-28 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work_01_app', '0002_alter_client_address_alter_client_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(null=True),
        ),
    ]
